version: 2

aliases:
  - &container_config
    docker:
      - image: circleci/node:8.9.4
    working_directory: /home/circleci/project

  - &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
    paths:
      - node_modules

  - &show_infomation
    name: Show system information.
    command: |
      echo "Node $(node -v)"
      echo "Npm $(npm -v)"

  - &restore_cache
    name: Restore Cache.
    <<: *node_modules_cache_params

  - &npm_install
    name: Set up to gas clasp enviroment.
    command: npm install

  - &save_cache
    name: Saving Cache.
    <<: *node_modules_cache_params

  - &lint
    name: Run Lint.
    command: npm run lint

  - &test
    name: Run Test.
    command: npm run test

  - &build
    name: Run webpack build.
    command: npm run build

  - &deploy
    name: Deploy to GAS.
    command: echo deploy

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: *show_infomation
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
      - run: *lint
      - run: *test
      - run: *build
  build_deploy:
    <<: *container_config
    steps:
      - checkout
      - run: *show_infomation
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
      - run: *lint
      - run: *test
      - run: *build
      - run: *deploy

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  build_deploy_workflow:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master
